mysql:
  build: docker/mysql
  ports:
    - 127.0.0.1:3311:3311
  environment:
    MYSQL_ROOT_PASSWORD: dronesimjira
    MYSQL_DATABASE: dronesimjira
    MYSQL_USER: dronesimjira
    MYSQL_PASSWORD: dronesimjira
  restart: always
jira:
  image: cptactionhank/atlassian-jira-software
  ports:
    - 127.0.0.1:8085:8080
  environment:
    X_PROXY_NAME: jira.colincampbell.me
    X_PROXY_PORT: 443
    X_PROXY_SCHEME: https
  volumes:
    - /var/jira/home:/var/atlassian/jira
    - /var/jira/logs:/opt/atlassian/jira/logs
  links:
    - mysql
  restart: always
